-- ============================================
-- SNOWFLAKE FILE PROCESSING PIPELINE
-- Database and RBAC Setup
-- ============================================
-- Purpose: Create database, schemas, and role hierarchy
-- 
-- This script creates:
--   1. Database and schemas (BRONZE, SILVER)
--   2. Three-tier RBAC hierarchy (ADMIN, READWRITE, READONLY)
--   3. Warehouses for compute
--   4. Initial grants and permissions
--
-- Role Hierarchy:
--   <DATABASE>_ADMIN (Full administrative access)
--       ↓ inherits
--   <DATABASE>_READWRITE (Execute procedures, operate tasks)
--       ↓ inherits
--   <DATABASE>_READONLY (Read-only access)
-- ============================================

-- ============================================
-- CONFIGURATION
-- ============================================

SET DATABASE_NAME = '$DATABASE_NAME';
SET BRONZE_SCHEMA_NAME = '$BRONZE_SCHEMA_NAME';
SET SILVER_SCHEMA_NAME = '$SILVER_SCHEMA_NAME';
SET WAREHOUSE_NAME = '$SNOWFLAKE_WAREHOUSE';
SET BRONZE_SCHEMA_FQN = $DATABASE_NAME || '.' || $BRONZE_SCHEMA_NAME;
SET SILVER_SCHEMA_FQN = $DATABASE_NAME || '.' || $SILVER_SCHEMA_NAME;
SET ADMIN_ROLE_NAME = $DATABASE_NAME || '_ADMIN';
SET READWRITE_ROLE_NAME = $DATABASE_NAME || '_READWRITE';
SET READONLY_ROLE_NAME = $DATABASE_NAME || '_READONLY';
SET ROLE_NAME_PATTERN = $DATABASE_NAME || '%';
SET ADMIN_ROLE_COMMENT = 'Full administrative access to ' || $DATABASE_NAME;
SET READWRITE_ROLE_COMMENT = 'Read/write access and procedure execution for ' || $DATABASE_NAME;
SET READONLY_ROLE_COMMENT = 'Read-only access to ' || $DATABASE_NAME;

-- ============================================
-- CREATE DATABASE AND SCHEMAS
-- ============================================

-- Use SYSADMIN role for database creation
USE ROLE SYSADMIN;

-- Create database (if not exists)
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DATABASE_NAME)
    COMMENT = 'Snowflake File Processing Pipeline with Bronze and Silver layers';

-- Create schemas
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($BRONZE_SCHEMA_FQN)
    COMMENT = 'Bronze Layer: Raw data ingestion from CSV and Excel files';

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SILVER_SCHEMA_FQN)
    COMMENT = 'Silver Layer: Transformed and quality-checked data';

-- ============================================
-- CREATE ROLE HIERARCHY
-- ============================================

-- Switch to SECURITYADMIN for account-level role management
USE ROLE SECURITYADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS IDENTIFIER($ADMIN_ROLE_NAME)
    COMMENT = $ADMIN_ROLE_COMMENT;

CREATE ROLE IF NOT EXISTS IDENTIFIER($READWRITE_ROLE_NAME)
    COMMENT = $READWRITE_ROLE_COMMENT;

CREATE ROLE IF NOT EXISTS IDENTIFIER($READONLY_ROLE_NAME)
    COMMENT = $READONLY_ROLE_COMMENT;

-- Set up role hierarchy (each role inherits from the one below)
GRANT ROLE IDENTIFIER($READONLY_ROLE_NAME) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT ROLE IDENTIFIER($READWRITE_ROLE_NAME) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

-- Grant admin role to SYSADMIN
GRANT ROLE IDENTIFIER($ADMIN_ROLE_NAME) TO ROLE SYSADMIN;

-- ============================================
-- DATABASE-LEVEL GRANTS
-- ============================================

-- Switch back to SYSADMIN for object grants
USE ROLE SYSADMIN;

-- ADMIN role: Full database access
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE_NAME) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT CREATE SCHEMA ON DATABASE IDENTIFIER($DATABASE_NAME) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT MONITOR ON DATABASE IDENTIFIER($DATABASE_NAME) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

-- READWRITE role: Usage only (inherits from READONLY)
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE_NAME) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

-- READONLY role: Usage only
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE_NAME) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

-- ============================================
-- SCHEMA-LEVEL GRANTS
-- ============================================

-- ADMIN role: Full schema access
GRANT ALL PRIVILEGES ON SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

-- READWRITE role: Usage and create objects
GRANT USAGE ON SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

-- READONLY role: Usage only
GRANT USAGE ON SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

GRANT USAGE ON SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

-- ============================================
-- FUTURE GRANTS (Auto-grant on new objects)
-- ============================================

-- ADMIN role: All privileges on future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

-- Same for Silver schema
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

-- READWRITE role: Select, Insert, Update, Delete on future tables
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON FUTURE STAGES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT OPERATE ON FUTURE TASKS IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

-- Same for Silver schema
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON FUTURE STAGES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT OPERATE ON FUTURE TASKS IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

-- READONLY role: Select only on future tables and views
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($BRONZE_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($SILVER_SCHEMA_FQN) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

-- ============================================
-- WAREHOUSE GRANTS
-- ============================================

-- Grant warehouse usage to all roles
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) 
    TO ROLE IDENTIFIER($ADMIN_ROLE_NAME);

GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) 
    TO ROLE IDENTIFIER($READWRITE_ROLE_NAME);

GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) 
    TO ROLE IDENTIFIER($READONLY_ROLE_NAME);

-- ============================================
-- TASK EXECUTION PRIVILEGES
-- ============================================
-- Note: EXECUTE TASK privilege must be granted by ACCOUNTADMIN
-- This is handled in Fix_Task_Privileges.sql

-- ============================================
-- SET DEFAULT CONTEXT
-- ============================================

USE ROLE IDENTIFIER($ADMIN_ROLE_NAME);
USE DATABASE IDENTIFIER($DATABASE_NAME);
USE SCHEMA IDENTIFIER($BRONZE_SCHEMA_NAME);
USE WAREHOUSE IDENTIFIER($WAREHOUSE_NAME);

-- ============================================
-- VERIFICATION
-- ============================================

-- Show created objects
SHOW DATABASES LIKE '%';
SHOW SCHEMAS IN DATABASE IDENTIFIER($DATABASE_NAME);
SHOW ROLES LIKE '%';

-- Display success message
SELECT 'Database and RBAC setup completed successfully' AS status,
       $DATABASE_NAME AS database_name,
       $BRONZE_SCHEMA_NAME AS bronze_schema,
       $SILVER_SCHEMA_NAME AS silver_schema,
       $ADMIN_ROLE_NAME AS admin_role,
       $READWRITE_ROLE_NAME AS readwrite_role,
       $READONLY_ROLE_NAME AS readonly_role;
